language: python
python:
  - 2.7
install:
  - "pip install -q git+git://github.com/crateio/recliner.git#egg=recliner"
  - pip install -q "file://$PWD#egg=warehouse[tests]"
script:
  - pep8 warehouse
  - pylint --rcfile .pylintrc -r y warehouse
  - py.test
